### ISSUE TITLE
show hits and order by hits for all urls page

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/shortlr2-backend#20]
on this page http://cb.lk/urls?all=true

**Comment by championswimmer** [comment]
@jatinkatyal13

**Comment by jatinkatyal13** [comment]
I think we should create a frontend for this because just for a viewing all the URLs sorted with number hits it would take 3 requests! Should I create a JQuery hack?

**Comment by championswimmer** [comment]
Just make the query `ORDER BY 'hits' DESC` no ?

**Comment by jatinkatyal13** [comment]
1st request to open the page, 2nd to show all URLs, 3rd to sort them!

**Comment by jatinkatyal13** [comment]
Not a good user experience

**Comment by championswimmer** [comment]
What are you saying ? I can't make any sense.

**Comment by jatinkatyal13** [comment]
Ohh so you mean by default all the URLs should be ordered by number of hits? Oh shit! I thought of creating a sort and filter kind of a thing we see in amazon and flipkart 😅

**Comment by championswimmer** [comment]
Yes by default, in the single query itself.
