### ISSUE TITLE
Create REST APIs

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/shortlr2-backend#96]
Create REST APIs that can handle

Get shortcode detail
```GET /api/:code```

Get all the links of the group
```GET /api/:groupCode/```

Get grouped shortcode details
```GET /api/:groupCode/:code```

Create shortcodes
```POST /api/```

**Comment by accakks** [comment]
I'd like to work on this, Please assign.

**Comment by Manit1** [comment]
@accakks sure! Anyone can work on the issue. Just make a PR referring this issue

**Comment by jatinkatyal13** [comment]
@accakks Sure! Anyone can work on it! Just make a PR referring this issue.
